- name: Copy RTPS package
  copy: src="{{ item }}" dest=/tmp/sip-rtps.rpm
  with_fileglob: ["../rpms/sip-rtps-*.rpm"]
- name: Install RTPS package
  yum: name=/tmp/sip-rtps.rpm state=present
  notify:
    - restart sip-rtps
- name: Install RTPS configuration file
  template: src=appl.conf dest=/opt/bda/sip-rtps/conf
  notify:
    - restart sip-rtps
- name: Create symbolink link to current Spark version
  file:
    src: /opt/mapr/spark/spark-2.2.1
    dest: /opt/mapr/spark/spark-current
    state: link
# Workaround: Installing the MapR HBase client gives empty entries in
# the classpath, which causes spark-submit to fail, as used by RTPS.
# So add a workaround to remove the empty entries before invoking
# spark-submit.
- name: Add workaround to remove empty entries from spark-submit classpath
  lineinfile:
    path: /opt/mapr/spark/spark-current/conf/spark-env.sh
    line: 'SPARK_SUBMIT_OPTS="$(echo $SPARK_SUBMIT_OPTS | sed -e s/=://g)"'
- name: Enable RTPS
  systemd: name=sip-rtps enabled=true state=started
