info:
  component: Synchronoss scheduler Service
spring:
  application:
    name: saw-sechduler-service
  #mariaDB (metadata) DB details
  datasource:
    url: jdbc:mariadb://localhost:3306/saw_scheduler
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    max-active: 25
    testOnBorrow: true
    testOnConnect: true
    testOnReturn: true
    validationQuery: SELECT 1
    testWhileIdle: true
    logValidationErrors: true
flyway.baselineOnMigrate: true
logging:
  level:
    com.synchronoss.saw.scheduler: INFO
    org.springframework: INFO
    org.hibernate.type : INFO

server:
  address: localhost
  port: 9601
  context-path: ''
  maxHttpHeaderSize: 65536
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
sip:
 service:
   index: 0
saw-analysis-service-url: http://localhost:9200/analysis
saw-dispatch-service-url: http://localhost:9400/exports
bis-transfer-url: http://localhost:9642/ingestion/batch/sftp/channel/transfers/data
       
