- name: Install EPEL release package (for NGINX)
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: Install NGINX package
  yum: name=nginx state=present
- name: Install NGINX SAW proxy configuration
  template: src=saw-proxy.conf dest=/etc/nginx/default.d
- name: Enable and start NGINX service
  systemd: name=nginx enabled=true state=started
